// src/lib/components/SocialLinks.svelte
<div class="mt-8 flex items-center gap-6">
	<a
		href="https://github.com/dibakarsutradhar"
		target="_blank"
		rel="noopener noreferrer"
		aria-label="GitHub"
		class="flex h-12 w-12 items-center justify-center rounded-full bg-card text-fg transition-all duration-300 hover:-translate-y-1 hover:bg-hover"
	>
		<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
			<path
				d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
			/>
		</svg>
	</a>

	<a
		href="https://www.linkedin.com/in/dibakarsutradhar"
		target="_blank"
		rel="noopener noreferrer"
		aria-label="LinkedIn"
		class="flex h-12 w-12 items-center justify-center rounded-full bg-card text-fg transition-all duration-300 hover:-translate-y-1 hover:bg-hover"
	>
		<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
			<path
				d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"
			/>
		</svg>
	</a>

	<a
		href="https://medium.com/@imdibakar"
		target="_blank"
		rel="noopener noreferrer"
		aria-label="Medium"
		class="flex h-12 w-12 items-center justify-center rounded-full bg-card text-fg transition-all duration-300 hover:-translate-y-1 hover:bg-hover"
	>
		<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
			<path
				d="M13.54 12a6.8 6.8 0 01-6.77 6.82A6.8 6.8 0 010 12a6.8 6.8 0 016.77-6.82A6.8 6.8 0 0113.54 12zM20.96 12c0 3.54-1.51 6.42-3.38 6.42-1.87 0-3.39-2.88-3.39-6.42s1.52-6.42 3.39-6.42 3.38 2.88 3.38 6.42M24 12c0 3.17-.53 5.75-1.19 5.75-.66 0-1.19-2.58-1.19-5.75s.53-5.75 1.19-5.75C23.47 6.25 24 8.83 24 12z"
			/>
		</svg>
	</a>

	<a
		href="mailto:iamdibakardipu@gmail.com"
		aria-label="Email"
		class="flex h-12 w-12 items-center justify-center rounded-full bg-card text-fg transition-all duration-300 hover:-translate-y-1 hover:bg-hover"
	>
		<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
			<path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
			<polyline points="22,6 12,13 2,6"></polyline>
		</svg>
	</a>
</div>

// components/SocialLinks.tsx
import Link from 'next/link';

const SOCIALS = [
	{
		label: 'GitHub',
		href: 'https://github.com/dibakarsutradhar',
		path: 'M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z'
	},
	{
		label: 'LinkedIn',
		href: 'https://www.linkedin.com/in/dibakarsutradhar',
		path: 'M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z'
	},
	{
		label: 'Medium',
		href: 'https://medium.com/@imdibakar',
		path: 'M13.54 12a6.8 6.8 0 01-6.77 6.82A6.8 6.8 0 010 12a6.8 6.8 0 016.77-6.82A6.8 6.8 0 0113.54 12zM20.96 12c0 3.54-1.51 6.42-3.38 6.42-1.87 0-3.39-2.88-3.39-6.42s1.52-6.42 3.39-6.42 3.38 2.88 3.38 6.42M24 12c0 3.17-.53 5.75-1.19 5.75-.66 0-1.19-2.58-1.19-5.75s.53-5.75 1.19-5.75C23.47 6.25 24 8.83 24 12z'
	}
];

/** Icon links shown under the role on the home page. */
export default function SocialLinks() {
	return (
		<div className="flex items-center gap-5">
			{SOCIALS.map((social) => (
				<a
					key={social.label}
					href={social.href}
					target="_blank"
					rel="noopener noreferrer"
					aria-label={social.label}
					className="flex h-12 w-12 items-center justify-center rounded-full bg-card text-fg transition-all duration-300 hover:-translate-y-1 hover:bg-hover"
				>
					<svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
						<path d={social.path} />
					</svg>
				</a>
			))}
			<a
				href="mailto:iamdibakardipu@gmail.com"
				aria-label="Email"
				className="flex h-12 w-12 items-center justify-center rounded-full bg-card text-fg transition-all duration-300 hover:-translate-y-1 hover:bg-hover"
			>
				<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
					<path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
					<polyline points="22,6 12,13 2,6" />
				</svg>
			</a>
			<Link
				href="/blog"
				aria-label="Blog"
				className="flex h-12 w-12 items-center justify-center rounded-full bg-card text-fg transition-all duration-300 hover:-translate-y-1 hover:bg-hover"
			>
				<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
					<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
					<path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
				</svg>
			</Link>
		</div>
	);
}
